# Site Info
title: finddme
#tagline: ''
#description: ''
url: http://finddme.github.io
logo: '/public/finddme.png'
encoding: utf-8
highlighter: rouge

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0


authoricon: heart

     

# About/contact
author:
  name: viein_serenity_singularity_simplicity_savage
  description: <strong>. </strong>viein
  #image: https://dPdlsdlek.github.io/public/img/yein01.jpeg
  #gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  gravatar: 753e5aac923755fc6a53de0a371ab12e
  
  contact:
    #linkedin:  
    email:     mailto:yein4452@yonsei.ac.kr
    github:    https://github.com/finddme
    #facebook:  
    #twitter:  <hide>
    #weibo:    <hide>
    

# Navigation (2nd level links supported)
nav:
  #Home: 
    #- '/'
  HOME: 
    - '/'
    # - '/blog/home/'
  # CATEGORIES: 
  #   - '/blog/categories/'
  
  CATEGORIES: 
    - '/blog/categories/'
    - { ⊹  All categories: '/blog/categories/' }
    - { ⊹  Portfolio: '/blog/portfolio/' }
    - { ⊹  LLM / Multimodal: '/blog/llm_multimodal/' }
    - { ⊹  NLP: '/blog/nlp/' }
    - { ⊹  NLP and Linguistics: '/blog/nlp_linguistics/' }
    - { ⊹  etc.: '/blog/etc/' }
  #TAGS: 
   # - '/blog/tags/'
  #Contents:           
    #- '/blog/'
    #- { Categories: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
  ABOUT:          
    - '/about/'

newhomenav:
  #Home: 
    #- '/'
  # ∙ Portfolio: 
  #   - '/blog/portfolio/'
  ∙ Project: 
    - '/blog/project/'
  ∙ Multimodal:
    - '/blog/multimodal/'
  ∙ Natural Language Processing: 
    - '/blog/nlp/'
  ∙ Natural Language Processing and Linguistics: 
    - '/blog/nlp_linguistics/'
  ∙ etc.: 
  - '/blog/etc/'
  #TAGS: 
   # - '/blog/tags/'
  #Contents:           
    #- '/blog/'
    #- { Categories: '/blog/categories/' }
    #- { Tags: '/blog/tags/' }
  # ABOUT:          
  #   - '/about/'
    
# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image : '/public/ggone.PNG'
#  image: https://dPdlsdlek.github.io/public/oz.jpg
#  caption: Original Artwork &copy; Pablo Picasso. Girl before a Mirror. Boisgeloup, March 1932. Oil on canvas
back: 
  image: https://finddme.github.io/public/oz.jpg

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'G-S91SD1WYXX' # leave blank if you don't want google analytics
disqus_short_name: 'dPdlsdlek-github-io' # leave blank if you don't want disqus

# Math equation
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Analytics
#analytics:
  #provider: "google"
  #google:
    #tracking_id: "G-S91SD1WYXX"
    #anonymize_ip: false # default

# # dark mode
# dark_theme_toggle        : true 
#   - /assets/js/custom/dark-theme.js
